project_id = "wfkfncbdarqahgqpmukv"

[functions.generate-meal-plan]
verify_jwt = false

[functions.product-recommendations]
verify_jwt = false

[functions.list-recommendations]
verify_jwt = false

[functions.import-product-prices]
verify_jwt = false